# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0ciart.indexer\"*\n\tImageData\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1a\n\nStringData\x12\x0c\n\x04text\x18\x02 \x01(\t\"6\n\x07\x43oncept\x12\x0f\n\x07\x63oncept\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04prob\x18\x03 \x01(\x02\"K\n\x10\x43lassifierResult\x12\x0e\n\x06plugin\x18\x01 \x01(\t\x12\'\n\x08\x63oncepts\x18\x02 \x03(\x0b\x32\x15.iart.indexer.Concept\"\x1f\n\rBinaryFeature\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t\"7\n\x07\x46\x65\x61ture\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x03(\x02\"H\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\"R\n\x04Pose\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.iart.indexer.PoseType\x12\t\n\x01x\x18\x02 \x03(\x02\x12\t\n\x01y\x18\x03 \x03(\x02\x12\x0e\n\x06scores\x18\x04 \x03(\x02\"\xf1\x02\n\nPluginData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12(\n\x05image\x18\x03 \x01(\x0b\x32\x17.iart.indexer.ImageDataH\x00\x12*\n\x06string\x18\x04 \x01(\x0b\x32\x18.iart.indexer.StringDataH\x00\x12\x34\n\nclassifier\x18\x05 \x01(\x0b\x32\x1e.iart.indexer.ClassifierResultH\x00\x12(\n\x07\x66\x65\x61ture\x18\x06 \x01(\x0b\x32\x15.iart.indexer.FeatureH\x00\x12\x34\n\rbinary_eature\x18\x07 \x01(\x0b\x32\x1b.iart.indexer.BinaryFeatureH\x00\x12\x31\n\x0c\x62ounding_box\x18\x08 \x01(\x0b\x32\x19.iart.indexer.BoundingBoxH\x00\x12\"\n\x04pose\x18\t \x01(\x0b\x32\x12.iart.indexer.PoseH\x00\x42\x06\n\x04\x64\x61ta*\x1e\n\x08PoseType\x12\x12\n\x0ePOSE_TYPE_COCO\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSETYPE']._serialized_start=853
  _globals['_POSETYPE']._serialized_end=883
  _globals['_IMAGEDATA']._serialized_start=28
  _globals['_IMAGEDATA']._serialized_end=70
  _globals['_STRINGDATA']._serialized_start=72
  _globals['_STRINGDATA']._serialized_end=98
  _globals['_CONCEPT']._serialized_start=100
  _globals['_CONCEPT']._serialized_end=154
  _globals['_CLASSIFIERRESULT']._serialized_start=156
  _globals['_CLASSIFIERRESULT']._serialized_end=231
  _globals['_BINARYFEATURE']._serialized_start=233
  _globals['_BINARYFEATURE']._serialized_end=264
  _globals['_FEATURE']._serialized_start=266
  _globals['_FEATURE']._serialized_end=321
  _globals['_BOUNDINGBOX']._serialized_start=323
  _globals['_BOUNDINGBOX']._serialized_end=395
  _globals['_POSE']._serialized_start=397
  _globals['_POSE']._serialized_end=479
  _globals['_PLUGINDATA']._serialized_start=482
  _globals['_PLUGINDATA']._serialized_end=851
# @@protoc_insertion_point(module_scope)
